theme = "native"
icons = "awesome5"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1
format = "{utilization} {frequency}"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "net"
format = "{ssid} {signal_strength} {ip} {speed_down}"
interval = 5
use_bits = false

[[block]]
block = "battery"
interval = 10
driver = "upower"
format = "{percentage}% {time}"

[[block]]
block = "backlight"

[[block]]
block = "sound"
format = "{volume}"

[block.mappings]
"alsa_output.usb-Harman_Multimedia_JBL_Pebbles_1.0.0-00.analog-stereo" = "🔈"
"alsa_output.pci-0000_00_1b.0.analog-stereo" = "🎧"

[[block]]
block = "time"
interval = 1
format = "%T 📅%F ⭐%w"

